#TO DISABLE AUTO RUN OF JOBS
spring:
  datasource:    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    hikari:
      data-source-properties:
        useSSL: false
        createDatabaseIfNotExist: true     jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  batch:
    initialize-schema: ALWAYS    job:      enabled: false

app:
  tasklet:
    input:
      file-path: E:\\batch
